import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import { signIn } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const handleSignIn = () => {
    signIn(undefined, { callbackUrl: "/prediction" });
  };
  return (
    <>
      <Head>
        <title>Hackathon project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div
          className="hero min-h-screen"
          style={{
            backgroundImage: `url(./images/background-ia-home.jpeg)`,
          }}
        >
          <div className="hero-overlay bg-opacity-60"></div>
          <div className="hero-content text-center text-neutral-content">
            <div className="max-w-md">
              <h1 className="mb-5 text-5xl font-bold text-white">
                Hello there
              </h1>
              <p className="mb-5 text-white text-xl">Login to start playing</p>
              <button className="btn btn-primary" onClick={handleSignIn}>
                Login with google
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
